export enum Status {
  CANCEL = 'CANCEL',
  DONE = 'DONE',
  READY_TO_TEST = 'READY_TO_TEST',
  READY_TO_DEVELOP = 'READY_TO_DEVELOP',
  IN_PROGRESS = 'IN_PROGRESS',
  READY_TO_CONFIRM = 'READY_TO_CONFIRM',
  PENDING = 'PENDING',
  BACKLOG = 'BACKLOG',
}
